version: "3.8"
services:
  web:
    build: ./app
    image: 920523009299.dkr.ecr.us-east-1.amazonaws.com/todoapp:todoapp_web
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=todo_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=tododb.cux067dei5lf.us-east-1.rds.amazonaws.com
      - DB_PORT=5431
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-52-7-239-141.compute-1.amazonaws.com
      - VIRTUAL_PORT=8000
volumes:
  static_volume: